crud_app/urls.py
from django.urls import path

from crud_app import views

app_name = 'crud_app'

urlpatterns = [
    # C
    path('create/', views.task_create_view, name='task_create_view'),
    # R
    path('list/', views.task_list_view, name='task_list_view'),  # list
    path('<int:pk>/', views.task_detail_view, name='task_detail_view'),  # detail
    # U
    path('update/<int:pk>/', views.task_update_view, name='task_update_view'),
    # D
    path('delete/<int:pk>/', views.task_delete_view, name='task_delete_view'),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include
from hello import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('Ilona/', views.Ilona),
    path('hi/', views.hi),
    path('hi2/', views.hi2),
    path('pikatchu/', views.pikatchu),
    path('pikatchu/pokemon-go', views.pokemonGo),

    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
    path('message/', include('message_app.urls')),
    path('view/', include('view_app.urls')),
    path('state/', include('state_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('dogs/', include('api_app.urls')),
]

crud_app/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

crud_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from crud_app.models import Task


def task_create_view(request):
    if request.method == "GET":
        return render(
            request,
            'crud_app/task_form.html',
        )

    if request.method == "POST":
        task = request.POST.get('task')
        if task:
            # zapis do tabeli Task
            Task.objects.create(name=task)

        return redirect("crud_app:task_list_view")


def task_list_view(request):
    # odczyt z tabeli Task
    tasks = Task.objects.all()

    return render(
        request,
        'crud_app/task_list.html',
        context={
            'tasks': tasks,
        }
    )


def task_detail_view(request, pk):
    # task = Task.objects.get(id=pk)
    task = get_object_or_404(Task, id=pk)

    return render(
        request,
        'crud_app/task_detail.html',
        context={
            'task': task,
        }
    )


def task_update_view(request, pk):
    task = get_object_or_404(Task, id=pk)

    if request.method == "GET":
        return render(
            request,
            'crud_app/task_update.html',
            context={
                'task': task,
            }
        )

    if request.method == "POST":
        task_new_name = request.POST.get('task')
        if task_new_name:
            task.name = task_new_name
            task.save()

        return redirect("crud_app:task_list_view")


def task_delete_view(request, pk):
    task = get_object_or_404(Task, id=pk)

    if request.method == "GET":
        return render(
            request,
            'crud_app/task_confirm_delete.html',
            context={
                'task': task,
            }
        )

    if request.method == "POST":
        res = request.POST.get('accept')
        if res:
            task.delete()

        return redirect("crud_app:task_list_view")

crud_app/templates/crud_app/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Czy na pewno chcesz usunąć task o numerze {{ task.id }} ({{ task.name }})?</h1>
  <form method="POST">{% csrf_token %}
      <input type="submit" name="accept" value="TAK">
      <input type="submit" name="reject" value="NIE">
  </form>
</body>
</html>

crud_app/templates/crud_app/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Szczegóły zadania o numerze {{ task.id }}</h1>
    <p>Nazwa: {{ task.name }}</p>
    <a href="{% url 'crud_app:task_list_view' %}"><button>Powrót do listy zadań</button></a>
</body>
</html>

crud_app/templates/crud_app/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Dodaj zadanie:</h2>
  <form method="POST">
      {% csrf_token %}
      <input type="text" placeholder="zadanie" name="task">
      <input type="submit" value="Dodaj">
  </form>
</body>
</html>

crud_app/templates/crud_app/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista zadań</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body style="margin: 1em;">
  <a href="{% url 'crud_app:task_create_view' %}"><button class="btn btn-success">Dodaj nowe zadanie</button></a>
  <h2>Lista zadań:</h2>
  <ul class="list-group list-group-flush">
    {% for task in tasks %}
      <li class="list-group-item">
          <a href="{% url 'crud_app:task_detail_view' task.id %}">{{ task.name }}</a>
          <a href="{% url 'crud_app:task_update_view' task.id %}"><button class="btn btn-primary">Zmień</button></a>
          <a href="{% url 'crud_app:task_delete_view' task.id %}"><button class="btn btn-danger">Usuń</button></a>
      </li>
      </li>
    {% endfor %}
  </ul>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

crud_app/templates/crud_app/task_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Modyfikacja zadania o numerze {{ task.id }}:</h2>
  <form method="POST">
      {% csrf_token %}
      <input type="text" placeholder="zadanie" name="task" value="{{ task.name }}">
      <input type="submit" value="Zmodyfikuj">
  </form>
  <a href="{% url 'crud_app:task_list_view' %}"><button style="margin-top:1em;">Anuluj</button></a>
</body>
</html>