intro/urls.py
from django.contrib import admin
from django.urls import path, include
from hello import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('Ilona/', views.Ilona),
    path('hi/', views.hi),
    path('hi2/', views.hi2),
    path('pikatchu/', views.pikatchu),
    path('pikatchu/pokemon-go', views.pokemonGo),

    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
    path('message/', include('message_app.urls')),
    path('view/', include('view_app.urls')),
    path('state/', include('state_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('dogs/', include('api_app.urls')),
]

links/urls.py
from django.urls import path
from links import views


app_name = 'links'
urlpatterns = [
    path('first/', views.first_view, name='first_name'),
    path('second/', views.second_view, name='second_name'),
    path('third/', views.third_view, name='third_name'),
]

links/views.py
from django.shortcuts import render

# Create your views here.
def first_view(request):
    return render(
        request,
        'links/first_template.html',
    )

def second_view(request):
    return render(
        request,
        'links/second_template.html',
    )

def third_view(request):
    return render(
        request,
        'links/third_template.html',
    )

links/templates/links/first_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <h1>To jest piewsza strona</h1>
 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, consequuntur doloribus eveniet minus nemo
 nihil praesentium quae reiciendis voluptate voluptates? Fuga id
     nam optio quia quod soluta veniam veritatis voluptatem!</p>

<p>Przejdź do strony <a href="{% url 'links:second_name' %}"> drugiej</a></p>

</body>
</html>

links/templates/links/second_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>To jest druga strona</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab amet dicta ducimus eos expedita fugiat,
fugit incidunt ipsa, itaque nisi obcaecati odit perferendis qui quod ratione reiciendis sequi temporibus vitae?</p>

<!-- <p>Przejdź do strony <a href="/links/first"> pierwszej</a></p> -->
<p>Przejdź do strony <a href="{% url 'links:third_name' %} "> trzeciej</a></p>

</body>
</html>

links/templates/links/third_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>To jest trzecia strona</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab amet dicta ducimus eos expedita fugiat,
fugit incidunt ipsa, itaque nisi obcaecati odit perferendis qui quod ratione reiciendis sequi temporibus vitae?</p>


</body>
</html>